package model;
// Generated 22.8.2014 3:48:13 by Hibernate Tools 3.6.0



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer idacount;
     private String email;
     private String password;

    public Account() {
    }

    public Account(String email, String password) {
       this.email = email;
       this.password = password;
    }
   
    public Integer getIdacount() {
        return this.idacount;
    }
    
    public void setIdacount(Integer idacount) {
        this.idacount = idacount;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


