package model;
// Generated 23.8.2014 17:14:34 by Hibernate Tools 3.6.0



/**
 * InvoiceHasItemId generated by hbm2java
 */
public class InvoiceHasItemId  implements java.io.Serializable {


     private int invoiceIdinvoice;
     private int itemIditem;

    public InvoiceHasItemId() {
    }

    public InvoiceHasItemId(int invoiceIdinvoice, int itemIditem) {
       this.invoiceIdinvoice = invoiceIdinvoice;
       this.itemIditem = itemIditem;
    }
   
    public int getInvoiceIdinvoice() {
        return this.invoiceIdinvoice;
    }
    
    public void setInvoiceIdinvoice(int invoiceIdinvoice) {
        this.invoiceIdinvoice = invoiceIdinvoice;
    }
    public int getItemIditem() {
        return this.itemIditem;
    }
    
    public void setItemIditem(int itemIditem) {
        this.itemIditem = itemIditem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoiceHasItemId) ) return false;
		 InvoiceHasItemId castOther = ( InvoiceHasItemId ) other; 
         
		 return (this.getInvoiceIdinvoice()==castOther.getInvoiceIdinvoice())
 && (this.getItemIditem()==castOther.getItemIditem());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInvoiceIdinvoice();
         result = 37 * result + this.getItemIditem();
         return result;
   }   


}


