package model;
// Generated 27.8.2014 20:47:12 by Hibernate Tools 3.6.0



/**
 * InvoiceHasPerson generated by hbm2java
 */
public class InvoiceHasPerson  implements java.io.Serializable {


     private Integer id;
     private int invoiceIdinvoice;
     private int personIdperson;
     private boolean relation;

    public InvoiceHasPerson() {
    }

    public InvoiceHasPerson(int invoiceIdinvoice, int personIdperson, boolean relation) {
       this.invoiceIdinvoice = invoiceIdinvoice;
       this.personIdperson = personIdperson;
       this.relation = relation;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getInvoiceIdinvoice() {
        return this.invoiceIdinvoice;
    }
    
    public void setInvoiceIdinvoice(int invoiceIdinvoice) {
        this.invoiceIdinvoice = invoiceIdinvoice;
    }
    public int getPersonIdperson() {
        return this.personIdperson;
    }
    
    public void setPersonIdperson(int personIdperson) {
        this.personIdperson = personIdperson;
    }
    public boolean isRelation() {
        return this.relation;
    }
    
    public void setRelation(boolean relation) {
        this.relation = relation;
    }




}


