package model;
// Generated 23.8.2014 17:14:34 by Hibernate Tools 3.6.0



/**
 * InvoiceHasPerson generated by hbm2java
 */
public class InvoiceHasPerson  implements java.io.Serializable {


     private InvoiceHasPersonId id;
     private boolean payer;

    public InvoiceHasPerson() {
    }

    public InvoiceHasPerson(InvoiceHasPersonId id, boolean payer) {
       this.id = id;
       this.payer = payer;
    }
   
    public InvoiceHasPersonId getId() {
        return this.id;
    }
    
    public void setId(InvoiceHasPersonId id) {
        this.id = id;
    }
    public boolean isPayer() {
        return this.payer;
    }
    
    public void setPayer(boolean payer) {
        this.payer = payer;
    }




}


