package model;
// Generated 22.8.2014 3:48:13 by Hibernate Tools 3.6.0



/**
 * InvoiceHasPersonId generated by hbm2java
 */
public class InvoiceHasPersonId  implements java.io.Serializable {


     private int invoiceIdinvoice;
     private int personIdperson;

    public InvoiceHasPersonId() {
    }

    public InvoiceHasPersonId(int invoiceIdinvoice, int personIdperson) {
       this.invoiceIdinvoice = invoiceIdinvoice;
       this.personIdperson = personIdperson;
    }
   
    public int getInvoiceIdinvoice() {
        return this.invoiceIdinvoice;
    }
    
    public void setInvoiceIdinvoice(int invoiceIdinvoice) {
        this.invoiceIdinvoice = invoiceIdinvoice;
    }
    public int getPersonIdperson() {
        return this.personIdperson;
    }
    
    public void setPersonIdperson(int personIdperson) {
        this.personIdperson = personIdperson;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoiceHasPersonId) ) return false;
		 InvoiceHasPersonId castOther = ( InvoiceHasPersonId ) other; 
         
		 return (this.getInvoiceIdinvoice()==castOther.getInvoiceIdinvoice())
 && (this.getPersonIdperson()==castOther.getPersonIdperson());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInvoiceIdinvoice();
         result = 37 * result + this.getPersonIdperson();
         return result;
   }   


}


