package model;
// Generated 22.8.2014 3:48:13 by Hibernate Tools 3.6.0



/**
 * InvoiceHasItem generated by hbm2java
 */
public class InvoiceHasItem  implements java.io.Serializable {


     private InvoiceHasItemId id;
     private int count;

    public InvoiceHasItem() {
    }

    public InvoiceHasItem(InvoiceHasItemId id, int count) {
       this.id = id;
       this.count = count;
    }
   
    public InvoiceHasItemId getId() {
        return this.id;
    }
    
    public void setId(InvoiceHasItemId id) {
        this.id = id;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }




}


