package model;
// Generated 22.8.2014 3:48:13 by Hibernate Tools 3.6.0



/**
 * Method generated by hbm2java
 */
public class Method  implements java.io.Serializable {


     private Integer idmethod;
     private String title;

    public Method() {
    }

    public Method(String title) {
       this.title = title;
    }
   
    public Integer getIdmethod() {
        return this.idmethod;
    }
    
    public void setIdmethod(Integer idmethod) {
        this.idmethod = idmethod;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


