package model;
// Generated 23.8.2014 17:14:34 by Hibernate Tools 3.6.0



/**
 * Rate generated by hbm2java
 */
public class Rate  implements java.io.Serializable {


     private Integer idrate;
     private String title;
     private int value;

    public Rate() {
    }

    public Rate(String title, int value) {
       this.title = title;
       this.value = value;
    }
   
    public Integer getIdrate() {
        return this.idrate;
    }
    
    public void setIdrate(Integer idrate) {
        this.idrate = idrate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


