package model;
// Generated 23.8.2014 17:14:34 by Hibernate Tools 3.6.0



/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private Integer idstate;
     private String title;

    public State() {
    }

    public State(String title) {
       this.title = title;
    }
   
    public Integer getIdstate() {
        return this.idstate;
    }
    
    public void setIdstate(Integer idstate) {
        this.idstate = idstate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


