package model;
// Generated 27.8.2014 20:47:12 by Hibernate Tools 3.6.0



/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private Integer id;
     private String title;

    public State() {
    }

    public State(String title) {
       this.title = title;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


